### ISSUE TITLE
Fix: Account-Setting Page >> Components-Overlapping-on-Zoom

### ISSUE THREAD

**Issue by faisalnazir7** [faisalnazir7/battleHost-frontend#244]

**Comment by sudhz** [comment]
can you please elaborate your issue? I would like to work on this

**Comment by sudhz** [comment]
I think I need to set the correct environment variables to reproduce this issue locally. Any ideas on how to produce it locally?

**Comment by faisalnazir7** [comment]
> I think I need to set the correct environment variables to reproduce this issue locally. Any ideas on how to reproduce it locally?

You can find .env.example in this repo, make a .env(your own key-values) in the root directory.

**Comment by sudhz** [comment]
I tried registering for a new user and logging in on my local environment after running a development server, but when I click on "register" it says something like "request blocked due to CORS policy".

I have tried many workarounds like disabling Firefox CORS policy from about:config and using the Allow-CORS extension, but still the error is there. I need to login in order to get to the user profile page to replicate this bug on my local system. Could someone please guide me if I'm doing something wrong here?

**Comment by faisalnazir7** [comment]
You will find backend-repo as well on my GitHub. Try to setup backend on your local machine as well.

**Comment by sudhz** [comment]
Oh okay, got it
